version: '3.8'

services:
  # PHP + Apache service
  web:
    container_name: api_ixc_pay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://myuser:mypassword@db:3306/ixcpay?serverVersion=8.0&charset=utf8mb4
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MySQL service
  db:
    container_name: ixcpay_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ixcpay
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    container_name: ixc_pay_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=myuser
      - PMA_PASSWORD=mypassword
    depends_on:
      - db

volumes:
  mysql_data: 